# Generated by Django 2.0.3 on 2018-03-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ventures',
        ),
        migrations.DeleteModel(
            name='Ventures_Request',
        ),
        migrations.RemoveField(
            model_name='startups',
            name='start_up_members',
        ),
        migrations.RemoveField(
            model_name='startups',
            name='start_up_sal',
        ),
        migrations.RemoveField(
            model_name='startups',
            name='start_up_skills_req',
        ),
    ]
