# Generated by Django 2.0.3 on 2018-03-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180324_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='StartUps',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
