# Generated by Django 2.0.3 on 2018-03-24 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180324_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menu_start_up_item', models.CharField(max_length=256)),
                ('Menu_start_up_item_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item', models.CharField(max_length=256)),
                ('order_price', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='StartUps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_up_name', models.CharField(max_length=256)),
                ('start_up_description', models.CharField(max_length=256)),
                ('start_up_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserDetails')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_start_up_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.StartUps'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserDetails'),
        ),
        migrations.AddField(
            model_name='menudetails',
            name='Menu_start_up_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.StartUps'),
        ),
    ]
