# Generated by Django 2.0.3 on 2018-03-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_userdetails_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudetails',
            name='Menu_start_up_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order_start_up_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='user_name',
            field=models.CharField(max_length=256),
        ),
    ]
